from lib.make_snippet import *

def test_1():  # basic functional test
    assert make_snippet1("one two three four five six") == "one two three four five six"

def test_2(): # check if adding .split() returns words split into a list
    assert make_snippet2("one two three four five six") == ['one', 'two', 'three', 'four', 'five', 'six']

def test_3():  # check len() returns True with string of 5 or less words
    assert make_snippet3("one two three four") == True

def test_3a():  # check len() returns True with string of 6 or more words 
    assert make_snippet3("one two three four five six") == None 

def test_4(): # check len() returns False with string of more than 5 words
    assert make_snippet4("one two three four five six") == False

def test_5(): # check .join() returns list *generated by .split()* converted back into a string
    assert make_snippet5("one two three four") == "one two three four"

def test_6():  # check else statement only returns 5 words
    assert make_snippet6("one two three four five six") == "one two three four five"

def test_7():  # check else statement now returns 5 words & " ..." suffix
    assert make_snippet7("one two three four five six") == "one two three four five ..."

def test_8():  # check what if/elif statement returns if no text entered
    assert make_snippet8("") == "No text entered"